### ISSUE TITLE
Crash when modded entity had tried to lay a egg

### ISSUE THREAD

**Issue by BearInBag** [joshiejack/Husbandry#3]
A tried to add support to Greater prairie chicken from from Unnamedanimalmod, but when chicken tried lay the egg in nest, minecraft crashed
[crash.txt](https://github.com/Harvest-Festival/Husbandry/files/6796989/crash.txt)
[Datapack.zip](https://github.com/Harvest-Festival/Husbandry/files/6796993/Datapack.zip)

**Comment by joshiejack** [comment]
Your loot table is a. csv file it should be .json

**Comment by joshiejack** [comment]
Also use a different namespace than husbandry. (using husbandry will overwrite the existing ones for the vanilla animals)

**Comment by joshiejack** [comment]
I will make the game not crash though in the future and put a warning that it couldn't find the loot table instead.
