### ISSUE TITLE
[Bug]Unlimited wool from shearing sheep

### ISSUE THREAD

**Issue by MisterObvious25** [joshiejack/Husbandry#4]
Forge version 36.1.0
Penguin-Lib 0.4.2
Husbandry 1.0.2

This was done in a new instance + new world. No other mods. 

Steps to reproduce:
1. Get vanilla shears
2. keep shearing sheep
3. Unlimited wool

**Comment by joshiejack** [comment]
Hmm I think I can see how this might be. I - did test it and it worked originally but since then I'd also added a check for the shears tag but I think I forgot some brackets. Will see when I'm home.
