### ISSUE TITLE
[Crash] Crash when sleeping with minecollonies citizens

### ISSUE THREAD

**Issue by AlienXtream** [joshiejack/Husbandry#5]
can not 100% confirm it is minecollonies but the game crashed after sleeping (or rather on wake up) only once i had started a town (and initial villagers had spawned)

[crash-2021-07-26_20.28.52-server.txt](https://github.com/Harvest-Festival/Husbandry/files/6877487/crash-2021-07-26_20.28.52-server.txt)

**Comment by joshiejack** [comment]
Not really sure how that would happen since i was purposefully avoiding that... in some way easy fix for it though, but i you made me look at that code and i noticed other issues with that :p
